export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  appPublicUrl: process.env.APP_PUBLIC_URL ?? "",
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID ?? "",
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN ?? "",
  twilioPhoneNumber: process.env.TWILIO_PHONE_NUMBER ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "coach@mindandbodyresetcoach.com",
  resendAudienceId: process.env.RESEND_AUDIENCE_ID ?? "",
  /** Svix signing secret from Resend webhook details (whsec_…) */
  resendWebhookSecret: process.env.RESEND_WEBHOOK_SECRET ?? "",
  fatsecretClientId: process.env.FATSECRET_CLIENT_ID ?? "",
  fatsecretClientSecret: process.env.FATSECRET_CLIENT_SECRET ?? "",
  /** OAuth 1.0 shared secret — Basic tier. Do not use the OAuth 2.0 Client Secret here. */
  fatsecretConsumerSecret: process.env.FATSECRET_CONSUMER_SECRET ?? "",
  ownerEmail: process.env.OWNER_EMAIL ?? "coach@mindandbodyresetcoach.com",
  metaConversionsApiToken: process.env.META_CONVERSIONS_API_TOKEN ?? "",
  metaPixelId: "1256633739205867",
  r2AccessKeyId: process.env.R2_ACCESS_KEY_ID ?? "",
  r2SecretAccessKey: process.env.R2_SECRET_ACCESS_KEY ?? "",
  r2Endpoint: process.env.R2_ENDPOINT ?? "",
  r2BucketName: process.env.R2_BUCKET_NAME ?? "mindbodyreset-assets",
  r2PublicUrl: process.env.R2_PUBLIC_URL ?? "https://pub-c6f7a165acb046c283b129a93cb2c8ec.r2.dev",
};
